services:
  zookeeper:
    image: bitnami/zookeeper:3.6.1
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_ENABLE_AUTH=yes
  kafka:
    image: bitnami/kafka:2.5.0
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ALLOW_PLAINTEXT_LISTENER=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT